-- Alignment of Dapodik Schema
-- 1. Students
ALTER TABLE students
ADD COLUMN IF NOT EXISTS nipd VARCHAR(50),
ADD COLUMN IF NOT EXISTS alamat_jalan TEXT,
ADD COLUMN IF NOT EXISTS no_hp VARCHAR(30),
ADD COLUMN IF NOT EXISTS email VARCHAR(100);

-- 2. Teachers
ALTER TABLE teachers
ADD COLUMN IF NOT EXISTS nuptk VARCHAR(50),
ADD COLUMN IF NOT EXISTS jk VARCHAR(10),
ADD COLUMN IF NOT EXISTS tempat_lahir VARCHAR(255),
ADD COLUMN IF NOT EXISTS tanggal_lahir DATE,
ADD COLUMN IF NOT EXISTS status_kepegawaian VARCHAR(100),
ADD COLUMN IF NOT EXISTS jenis_ptk VARCHAR(100),
ADD COLUMN IF NOT EXISTS agama VARCHAR(50),
ADD COLUMN IF NOT EXISTS alamat_jalan TEXT,
ADD COLUMN IF NOT EXISTS no_hp VARCHAR(30),
ADD COLUMN IF NOT EXISTS email VARCHAR(100);

-- 3. Staff
ALTER TABLE staff
ADD COLUMN IF NOT EXISTS nuptk VARCHAR(50),
ADD COLUMN IF NOT EXISTS jk VARCHAR(10),
ADD COLUMN IF NOT EXISTS tempat_lahir VARCHAR(255),
ADD COLUMN IF NOT EXISTS tanggal_lahir DATE,
ADD COLUMN IF NOT EXISTS nip VARCHAR(50),
ADD COLUMN IF NOT EXISTS status_kepegawaian VARCHAR(100),
ADD COLUMN IF NOT EXISTS jenis_ptk VARCHAR(100),
ADD COLUMN IF NOT EXISTS agama VARCHAR(50),
ADD COLUMN IF NOT EXISTS alamat_jalan TEXT,
ADD COLUMN IF NOT EXISTS no_hp VARCHAR(30),
ADD COLUMN IF NOT EXISTS email VARCHAR(100);

-- 4. Classes
ALTER TABLE classes
ADD COLUMN IF NOT EXISTS jenis_rombel VARCHAR(100),
ADD COLUMN IF NOT EXISTS tingkat VARCHAR(10),
ADD COLUMN IF NOT EXISTS kurikulum VARCHAR(100),
ADD COLUMN IF NOT EXISTS kompetensi_keahlian VARCHAR(255);
