[package]
name = "hash-gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hash-gen"
path = "src/main.rs"

[dependencies]
argon2 = { version = "0.5", features = ["std"] }
tokio = { version = "1.37", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
uuid = { version = "1.8", features = ["v4", "v7"] }
chrono = { version = "0.4", features = ["serde"] }



