use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Permission {
    StudentRead,
    StudentCreate,
    StudentUpdate,
    StudentDelete,
    TeacherRead,
    TeacherCreate,
    TeacherUpdate,
    TeacherDelete,
    GuardianRead,
    GuardianCreate,
    GuardianUpdate,
    GuardianDelete,
    StaffRead,
    StaffCreate,
    StaffUpdate,
    StaffDelete,
    AcademicManage,
    LearningCurriculumCreate,
    LearningCurriculumRead,
    LearningCurriculumUpdate,
    LearningCurriculumDelete,
    LearningSyllabusCreate,
    LearningSyllabusRead,
    LearningSyllabusUpdate,
    LearningSyllabusDelete,
    LearningMaterialCreate,
    LearningMaterialRead,
    LearningMaterialUpdate,
    LearningMaterialDelete,
    LearningLessonCreate,
    LearningLessonRead,
    LearningLessonUpdate,
    LearningLessonDelete,
    LearningSessionCreate,
    LearningSessionRead,
    LearningSessionUpdate,
    LearningSessionDelete,
    LearningAssignmentCreate,
    LearningAssignmentRead,
    LearningAssignmentUpdate,
    LearningAssignmentDelete,
    LearningQuizCreate,
    LearningQuizRead,
    LearningQuizUpdate,
    LearningQuizDelete,
    LearningAssessmentConfigure,
    LearningAssessmentRead,
    LearningProgressRead,
    LearningProgressUpdate,
    LearningAchievementCreate,
    LearningAchievementRead,
    LearningAchievementAward,
    LearningFeedCreate,
    LearningFeedRead,
    NotificationRead,
    NotificationUpdate,
    AssessmentInput,
    AssessmentRead,
    AttendanceRecord,
    AttendanceRead,
    SchoolUpdate,
    TenantManage,
    SystemInternal,
}

impl Permission {
    pub fn as_str(&self) -> &'static str {
        match self {
            Permission::StudentRead => "Student.Read",
            Permission::StudentCreate => "Student.Create",
            Permission::StudentUpdate => "Student.Update",
            Permission::StudentDelete => "Student.Delete",
            Permission::TeacherRead => "Teacher.Read",
            Permission::TeacherCreate => "Teacher.Create",
            Permission::TeacherUpdate => "Teacher.Update",
            Permission::TeacherDelete => "Teacher.Delete",
            Permission::GuardianRead => "Guardian.Read",
            Permission::GuardianCreate => "Guardian.Create",
            Permission::GuardianUpdate => "Guardian.Update",
            Permission::GuardianDelete => "Guardian.Delete",
            Permission::StaffRead => "Staff.Read",
            Permission::StaffCreate => "Staff.Create",
            Permission::StaffUpdate => "Staff.Update",
            Permission::StaffDelete => "Staff.Delete",
            Permission::AcademicManage => "Academic.Manage",
            Permission::LearningCurriculumCreate => "Learning.Curriculum.Create",
            Permission::LearningCurriculumRead => "Learning.Curriculum.Read",
            Permission::LearningCurriculumUpdate => "Learning.Curriculum.Update",
            Permission::LearningCurriculumDelete => "Learning.Curriculum.Delete",
            Permission::LearningSyllabusCreate => "Learning.Syllabus.Create",
            Permission::LearningSyllabusRead => "Learning.Syllabus.Read",
            Permission::LearningSyllabusUpdate => "Learning.Syllabus.Update",
            Permission::LearningSyllabusDelete => "Learning.Syllabus.Delete",
            Permission::LearningMaterialCreate => "Learning.Material.Create",
            Permission::LearningMaterialRead => "Learning.Material.Read",
            Permission::LearningMaterialUpdate => "Learning.Material.Update",
            Permission::LearningMaterialDelete => "Learning.Material.Delete",
            Permission::LearningLessonCreate => "Learning.Lesson.Create",
            Permission::LearningLessonRead => "Learning.Lesson.Read",
            Permission::LearningLessonUpdate => "Learning.Lesson.Update",
            Permission::LearningLessonDelete => "Learning.Lesson.Delete",
            Permission::LearningSessionCreate => "Learning.Session.Create",
            Permission::LearningSessionRead => "Learning.Session.Read",
            Permission::LearningSessionUpdate => "Learning.Session.Update",
            Permission::LearningSessionDelete => "Learning.Session.Delete",
            Permission::LearningAssignmentCreate => "Learning.Assignment.Create",
            Permission::LearningAssignmentRead => "Learning.Assignment.Read",
            Permission::LearningAssignmentUpdate => "Learning.Assignment.Update",
            Permission::LearningAssignmentDelete => "Learning.Assignment.Delete",
            Permission::LearningQuizCreate => "Learning.Quiz.Create",
            Permission::LearningQuizRead => "Learning.Quiz.Read",
            Permission::LearningQuizUpdate => "Learning.Quiz.Update",
            Permission::LearningQuizDelete => "Learning.Quiz.Delete",
            Permission::LearningAssessmentConfigure => "Learning.Assessment.Configure",
            Permission::LearningAssessmentRead => "Learning.Assessment.Read",
            Permission::LearningProgressRead => "Learning.Progress.Read",
            Permission::LearningProgressUpdate => "Learning.Progress.Update",
            Permission::LearningAchievementCreate => "Learning.Achievement.Create",
            Permission::LearningAchievementRead => "Learning.Achievement.Read",
            Permission::LearningAchievementAward => "Learning.Achievement.Award",
            Permission::LearningFeedCreate => "Learning.Feed.Create",
            Permission::LearningFeedRead => "Learning.Feed.Read",
            Permission::NotificationRead => "Notification.Read",
            Permission::NotificationUpdate => "Notification.Update",
            Permission::AssessmentInput => "Assessment.Input",
            Permission::AssessmentRead => "Assessment.Read",
            Permission::AttendanceRecord => "Attendance.Record",
            Permission::AttendanceRead => "Attendance.Read",
            Permission::SchoolUpdate => "School.Update",
            Permission::TenantManage => "Tenant.Manage",
            Permission::SystemInternal => "System.Internal",
        }
    }

    #[allow(clippy::should_implement_trait)]
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "Student.Read" => Some(Permission::StudentRead),
            "Student.Create" => Some(Permission::StudentCreate),
            "Student.Update" => Some(Permission::StudentUpdate),
            "Student.Delete" => Some(Permission::StudentDelete),
            "Teacher.Read" => Some(Permission::TeacherRead),
            "Teacher.Create" => Some(Permission::TeacherCreate),
            "Teacher.Update" => Some(Permission::TeacherUpdate),
            "Teacher.Delete" => Some(Permission::TeacherDelete),
            "Guardian.Read" => Some(Permission::GuardianRead),
            "Guardian.Create" => Some(Permission::GuardianCreate),
            "Guardian.Update" => Some(Permission::GuardianUpdate),
            "Guardian.Delete" => Some(Permission::GuardianDelete),
            "Staff.Read" => Some(Permission::StaffRead),
            "Staff.Create" => Some(Permission::StaffCreate),
            "Staff.Update" => Some(Permission::StaffUpdate),
            "Staff.Delete" => Some(Permission::StaffDelete),
            "Academic.Manage" => Some(Permission::AcademicManage),
            "Learning.Curriculum.Create" => Some(Permission::LearningCurriculumCreate),
            "Learning.Curriculum.Read" => Some(Permission::LearningCurriculumRead),
            "Learning.Curriculum.Update" => Some(Permission::LearningCurriculumUpdate),
            "Learning.Curriculum.Delete" => Some(Permission::LearningCurriculumDelete),
            "Learning.Syllabus.Create" => Some(Permission::LearningSyllabusCreate),
            "Learning.Syllabus.Read" => Some(Permission::LearningSyllabusRead),
            "Learning.Syllabus.Update" => Some(Permission::LearningSyllabusUpdate),
            "Learning.Syllabus.Delete" => Some(Permission::LearningSyllabusDelete),
            "Learning.Material.Create" => Some(Permission::LearningMaterialCreate),
            "Learning.Material.Read" => Some(Permission::LearningMaterialRead),
            "Learning.Material.Update" => Some(Permission::LearningMaterialUpdate),
            "Learning.Material.Delete" => Some(Permission::LearningMaterialDelete),
            "Learning.Lesson.Create" => Some(Permission::LearningLessonCreate),
            "Learning.Lesson.Read" => Some(Permission::LearningLessonRead),
            "Learning.Lesson.Update" => Some(Permission::LearningLessonUpdate),
            "Learning.Lesson.Delete" => Some(Permission::LearningLessonDelete),
            "Learning.Session.Create" => Some(Permission::LearningSessionCreate),
            "Learning.Session.Read" => Some(Permission::LearningSessionRead),
            "Learning.Session.Update" => Some(Permission::LearningSessionUpdate),
            "Learning.Session.Delete" => Some(Permission::LearningSessionDelete),
            "Learning.Assignment.Create" => Some(Permission::LearningAssignmentCreate),
            "Learning.Assignment.Read" => Some(Permission::LearningAssignmentRead),
            "Learning.Assignment.Update" => Some(Permission::LearningAssignmentUpdate),
            "Learning.Assignment.Delete" => Some(Permission::LearningAssignmentDelete),
            "Learning.Quiz.Create" => Some(Permission::LearningQuizCreate),
            "Learning.Quiz.Read" => Some(Permission::LearningQuizRead),
            "Learning.Quiz.Update" => Some(Permission::LearningQuizUpdate),
            "Learning.Quiz.Delete" => Some(Permission::LearningQuizDelete),
            "Learning.Assessment.Configure" => Some(Permission::LearningAssessmentConfigure),
            "Learning.Assessment.Read" => Some(Permission::LearningAssessmentRead),
            "Learning.Progress.Read" => Some(Permission::LearningProgressRead),
            "Learning.Progress.Update" => Some(Permission::LearningProgressUpdate),
            "Learning.Achievement.Create" => Some(Permission::LearningAchievementCreate),
            "Learning.Achievement.Read" => Some(Permission::LearningAchievementRead),
            "Learning.Achievement.Award" => Some(Permission::LearningAchievementAward),
            "Learning.Feed.Create" => Some(Permission::LearningFeedCreate),
            "Learning.Feed.Read" => Some(Permission::LearningFeedRead),
            "Notification.Read" => Some(Permission::NotificationRead),
            "Notification.Update" => Some(Permission::NotificationUpdate),
            "Assessment.Input" => Some(Permission::AssessmentInput),
            "Assessment.Read" => Some(Permission::AssessmentRead),
            "Attendance.Record" => Some(Permission::AttendanceRecord),
            "Attendance.Read" => Some(Permission::AttendanceRead),
            "School.Update" => Some(Permission::SchoolUpdate),
            "Tenant.Manage" => Some(Permission::TenantManage),
            "System.Internal" => Some(Permission::SystemInternal),
            _ => None,
        }
    }

    pub fn all() -> Vec<Self> {
        vec![
            Permission::StudentRead,
            Permission::StudentCreate,
            Permission::StudentUpdate,
            Permission::StudentDelete,
            Permission::TeacherRead,
            Permission::TeacherCreate,
            Permission::TeacherUpdate,
            Permission::TeacherDelete,
            Permission::GuardianRead,
            Permission::GuardianCreate,
            Permission::GuardianUpdate,
            Permission::GuardianDelete,
            Permission::StaffRead,
            Permission::StaffCreate,
            Permission::StaffUpdate,
            Permission::StaffDelete,
            Permission::AcademicManage,
            Permission::LearningCurriculumCreate,
            Permission::LearningCurriculumRead,
            Permission::LearningCurriculumUpdate,
            Permission::LearningCurriculumDelete,
            Permission::LearningSyllabusCreate,
            Permission::LearningSyllabusRead,
            Permission::LearningSyllabusUpdate,
            Permission::LearningSyllabusDelete,
            Permission::LearningMaterialCreate,
            Permission::LearningMaterialRead,
            Permission::LearningMaterialUpdate,
            Permission::LearningMaterialDelete,
            Permission::LearningLessonCreate,
            Permission::LearningLessonRead,
            Permission::LearningLessonUpdate,
            Permission::LearningLessonDelete,
            Permission::LearningSessionCreate,
            Permission::LearningSessionRead,
            Permission::LearningSessionUpdate,
            Permission::LearningSessionDelete,
            Permission::LearningAssignmentCreate,
            Permission::LearningAssignmentRead,
            Permission::LearningAssignmentUpdate,
            Permission::LearningAssignmentDelete,
            Permission::LearningQuizCreate,
            Permission::LearningQuizRead,
            Permission::LearningQuizUpdate,
            Permission::LearningQuizDelete,
            Permission::LearningAssessmentConfigure,
            Permission::LearningAssessmentRead,
            Permission::LearningProgressRead,
            Permission::LearningProgressUpdate,
            Permission::LearningAchievementCreate,
            Permission::LearningAchievementRead,
            Permission::LearningAchievementAward,
            Permission::LearningFeedCreate,
            Permission::LearningFeedRead,
            Permission::NotificationRead,
            Permission::NotificationUpdate,
            Permission::AssessmentInput,
            Permission::AssessmentRead,
            Permission::AttendanceRecord,
            Permission::AttendanceRead,
            Permission::SchoolUpdate,
            Permission::TenantManage,
            Permission::SystemInternal,
        ]
    }
}
